import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Starting Test Successful</h1>
        <button className="btn btn-primary">Button</button>
        <button className="btn btn-primary">Button added by joy</button>
      </main>
    </div>
  )
}
